wifis:
  network:
    ethernets:
      eth0:
        dhcp4: true
        optional: true
    version: 2
    wifis:
      wlan0:
        dhcp4: true
        optional: true
        access-points:
          "SSID_name":
            password: "WiFi_password"
